def get_GBM_feature_columns():
    return [
        "num_perimeters_0_5h",
        "dt_first_last_0_5h",
        "area_first_ha",
        "area_growth_abs_0_5h",
        "area_growth_rate_ha_per_h",
        "radial_growth_m",
        "radial_growth_rate_m_per_h",
        "area_growth_rel_0_5h",
        "log1p_area_first",
        "log1p_growth",
        "log_area_ratio_0_5h",
        "centroid_speed_m_per_h",
        "dist_min_ci_0_5h",
        "closing_speed_m_per_h",
        "dist_slope_ci_0_5h",
        "dist_change_ci_0_5h",
        "dist_std_ci_0_5h",
        "dist_fit_r2_0_5h",
        "alignment_cos",
        "along_track_speed",
        "event_start_hour",
        "event_start_dayofweek",
        "event_start_month",

        "growth_dist_interaction",
        "speed_alignment",
        "closing_ratio",
        "growth_acceleration",
        "log_dist",
        "inv_dist",
        "growth_over_dist",
        "hour_bucket",
        "movement_consistency",
        "area_ratio",
        "directional_risk",
        "growth_norm",
        "movement_strength",
    ]

def get_NN_feature_columns():
    return [
        "num_perimeters_0_5h",
        "dt_first_last_0_5h",
        "log1p_area_first",
        "log1p_growth",
        "log_area_ratio_0_5h",
        "area_growth_rate_ha_per_h",
        "radial_growth_rate_m_per_h",
        "area_growth_rel_0_5h",
        "centroid_speed_m_per_h",
        "dist_min_ci_0_5h",
        "closing_speed_m_per_h",
        "dist_slope_ci_0_5h",
        "dist_std_ci_0_5h",
        "alignment_cos",
        "along_track_speed",
        "event_start_hour",
        "event_start_dayofweek",
        "event_start_month",

        "growth_dist_interaction",
        "speed_alignment",
        "closing_ratio",
        "growth_acceleration",
        "log_dist",
        "inv_dist",
        "growth_over_dist",
        "hour_bucket",
        "movement_consistency",
        "area_ratio",
        "directional_risk",
        "growth_norm",
        "movement_strength",
    ]